---
title: "Exploratory Data Analysis"
description: |
  The site provides a collection of resources and summary reports containing statistics and other relevant information about the datasets.
site: distill::distill_website
---

```{r, setup, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
r_func_path <- "./_func"
r_funcs <- c("libraries.Rmd", "common.Rmd")
```

```{r, import, child=file.path(r_func_path, r_funcs)}
```

## Summary Reports

  * [Arctic Ocean Summary Report](https://aiqc-hub.github.io/arc-report/)
  * [Baltic Sea Summary Report](https://aiqc-hub.github.io/bal-report/)
  * [Mediterranean Sea Summary Report](https://aiqc-hub.github.io/med-report/)

---

## Original NetCDF Datasets
```{r, eda_netcdf, results = 'asis'}
src <- knitr::knit_expand(t_eda_netcdf)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## Exported Parquet Datasets
```{r, eda_parquet, results = 'asis'}
src <- knitr::knit_expand(t_eda_parquet)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## Duplicate Profiles
```{r, eda_duplicate, results = 'asis'}
src <- knitr::knit_expand(t_eda_duplicate)
res <- knitr::knit_child(text = src, quiet = TRUE)
cat(res, sep = '\n')
```

---

## Fraction of QC4 Flags per Profile
```{r, eda_qc4_fraction, results = 'asis'}
src <- knitr::knit_expand(t_eda_qc4_fraction)
cat(src, sep = '\n')
```

---

## Distributions of QC 1 & 4 Flags Over Time
```{r, eda_qc_over_time, results = 'asis'}
src <- knitr::knit_expand(t_eda_qc_over_time)
cat(src, sep = '\n')
```

---
