
## 3. Distributions by profile over time and location

```{r, echo = FALSE, message = FALSE, warning = FALSE, results = 'asis'}

summary_table_var3 <- var_summary_3(df_filtered, {{var}})

df_year <- summary_table_var3 %>%
  mutate(x = format(profile_timestamp, "%Y"))

df_month <- summary_table_var3 %>%
  mutate(x = format(profile_timestamp, "%m"))

```

### Year

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
p_year_bp <- create_var_boxplot(df_year, "{{var_name}}")

print(p_year_bp)
```

### Month

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
p_month_bp <- create_var_boxplot(df_month, "{{var_name}}")

print(p_month_bp)
```

### Longitude

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
p_longitude_dense <- create_var_density(summary_table_var3, longitude, "{{var_name}}")

print(p_longitude_dense)
```

### Latitude

```{r, echo = FALSE, message = FALSE, warning = FALSE, fig.width = 10}
p_latitude_hist <- create_var_density(summary_table_var3, latitude, "{{var_name}}")

print(p_latitude_hist)
```
